apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-front
  name: test-front-clusterip-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-front
  type: ClusterIP
