apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: test-app-ing
  namespace: default
spec:
  rules:
  - host: wiliot-test-app.ddns.net
    http:
      paths:
      - backend:
          service:
            name: test-app-clusterip-svc
            port:
              number: 8080
        path: /
        pathType: Prefix

