apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app-clusterip-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app
  type: ClusterIP
