apiVersion: v1
kind: Service
metadata:
  name: test-app-clusterip-svc-lb
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app
  type: LoadBalancer

